import rehypeCustomTocBase, { type RehypeCustomTocOptions, type RehypeCustomTocTemplate } from "rehype-custom-toc";
import type { Plugin } from "unified";
import type { Root } from "hast";
import type { VFile } from "vfile";

/**
 * A comment node generated by the `remark-comment` plugin.
 */
interface Comment extends Node {
    type: "comment";
    value: "";
    commentValue: string;
}

/**
 * Rehype plugin to generate a table of contents.
 * @param userOptions Options for the plugin
 * @returns The plugin
 */
const rehypeCustomToc: Plugin<[RehypeCustomTocOptions], Root> = (userOptions: RehypeCustomTocOptions) => {
    type RehypeCustomTocFactory = (options: RehypeCustomTocOptions) => ReturnType<typeof rehypeCustomTocBase>;
    const createBaseTransformer = rehypeCustomTocBase as RehypeCustomTocFactory;
    const transformer = createBaseTransformer(userOptions) as (tree: Root, file: VFile) => unknown;

    return (tree: Root, file) => {
        if (!file.data.astro?.frontmatter || file.data.astro.frontmatter["showToc"] !== true) return;
        void transformer(tree, file);
    };
};

export { type Comment, type RehypeCustomTocTemplate, type RehypeCustomTocOptions, rehypeCustomToc };
